apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-postgres
spec:
  selector:
    matchLabels:
      app: db-postgres
  template:
    metadata:
      labels:
        app: db-postgres
    spec:
      containers:
        - name: db-postgres
          image: postgres
          ports:
          - containerPort: 5432
          env:
          - name: POSTGRES_DB
            value: "database-kubenews"
          - name: POSTGRES_USER
            value: "user"
          - name: POSTGRES_PASSWORD
            value: "pwd1234"  

---
apiVersion: v1
kind: Service
metadata:
  name: db-postgres
spec:
  selector: 
    app: db-postgres
  ports:
    - port: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-kubenews
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-kubenews
  template:
    metadata:
      labels:
        app: app-kubenews
    spec:
      containers:
        - name: app-kubenews
          image: evertonhub/kube-news:latest
          ports:
          - containerPort: 8080
          env:
          - name: DB_DATABASE
            value: "database-kubenews"
          - name: DB_USERNAME
            value: "user"
          - name: DB_PASSWORD
            value: "pwd1234" 
          - name: DB_HOST
            value: "db-postgres"  
---
apiVersion: v1
kind: Service
metadata:
  name: app-kubenews
spec:
  selector: 
    app: app-kubenews
  ports:
    - port: 80
      targetPort: 8080
# type: ClusterIP
  type: LoadBalancer
