name: CI-CD
on: 
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker build kube-news
        uses: docker/build-push-action@v4.1.1
        with:
          context: ./src
          file: ./scr/Dockerfile
          push: true
          tags:
            evertonhub/kube-news:v1
            evertonhub/kube-news:latest
    
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - uses: actions/checkout@v3
      - name: Autenticar o AWS CLI
        run: echo "Configurar o AWS configure"
      - name: Configuração do kubectl
        run: echo "Configurar o kubectl"
      - name: Deploy dos apps
        run: echo "exec deploy dos apps"
